//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQ_DescriptionDecoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQ_DescriptionDecoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Rung Number=&quot;0&quot; Type=&quot;N&quot;&gt;
        ///&lt;Text&gt;
        ///&lt;![CDATA[XIC(TAG_1.HOA.14)XIO(TAG_1.Alarm.Disabled)OTL(TAG_1.Alarm.Value);]]&gt;
        ///&lt;/Text&gt;
        ///&lt;/Rung&gt;
        ///&lt;Rung Number=&quot;1&quot; Type=&quot;N&quot;&gt;
        ///&lt;Text&gt;
        ///&lt;![CDATA[[XIO(TAG_1.HOA.14) XIC(TAG_1.Alarm.Acknowledge) OTU(TAG_1.Alarm.Value) ,XIC(TAG_1.Alarm.Value) XIC(Alarm_Acknowledge) OTL(TAG_1.Alarm.Acknowledge) ,XIO(TAG_1.Alarm.Value) OTU(TAG_1.Alarm.Acknowledge) ];]]&gt;
        ///&lt;/Text&gt;
        ///&lt;/Rung&gt;.
        /// </summary>
        internal static string AlarmRungsExport {
            get {
                return ResourceManager.GetString("AlarmRungsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;Rung Number=&quot;0&quot; Type=&quot;N&quot;&gt;
        ///			&lt;Comment&gt;
        ///			&lt;![CDATA[HOA]]&gt;
        ///			&lt;/Comment&gt;
        ///			&lt;Text&gt;
        ///			&lt;![CDATA[XIC(VFD800.HOA.1)TOF(VFD800.DelayBeforeOffTimer,?,?);]]&gt;
        ///			&lt;/Text&gt;
        ///			&lt;/Rung&gt;
        ///			&lt;Rung Number=&quot;1&quot; Type=&quot;N&quot;&gt;
        ///			&lt;Text&gt;
        ///			&lt;![CDATA[[XIC(VFD800.HOA.12) [XIC(VFD800.HOA.1) ,XIC(VFD800.DelayBeforeOffTimer.DN) ] XIO(VFD800.HOA.3) ,XIO(VFD800.HOA.12) [XIC(VFD800.HOA.2) ,XIC(VFD800.HOA.24) ] XIO(VFD800.HOA.4) ]OTE(VFD800.Value);]]&gt;
        ///			&lt;/Text&gt;
        ///			&lt;/Rung&gt;
        ///			&lt;Rung Number=&quot;2&quot; Type=&quot;N&quot;&gt;
        ///			&lt;Text&gt;
        ///			&lt;![CDA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HOA {
            get {
                return ResourceManager.GetString("HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*********************************************
        ///
        ///  Import-Export
        ///  Version   := RSLogix 5000 v30.00
        ///  Owner     := IQC, 
        ///  Exported  := Sat Feb 27 12:12:08 2021
        ///
        ///  Note:  File encoded in UTF-8.  Only edit file in a program 
        ///         which supports UTF-8 (like Notepad, not Wordpad).
        ///
        ///**********************************************)
        ///IE_VER := 2.21;
        ///
        ///CONTROLLER SIR_Mixer8_Test_R1 (ProcessorType := &quot;5069-L330ER&quot;,
        ///                               Major := 30,
        ///                               RedundancyE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Comment Operand=&quot;.HOA.0&quot;&gt;
        ///&lt;![CDATA[
        ///Output On]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.1&quot;&gt;
        ///&lt;![CDATA[
        ///Request Auto On]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.2&quot;&gt;
        ///&lt;![CDATA[
        ///Request Manual On]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.3&quot;&gt;
        ///&lt;![CDATA[
        ///Interlocked Off For Auto Mode]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.4&quot;&gt;
        ///&lt;![CDATA[
        ///Interlocked Off For Manual Mode]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.5&quot;&gt;
        ///&lt;![CDATA[
        ///Simulation Bit]]&gt;
        ///&lt;/Comment&gt;
        ///&lt;Comment Operand=&quot;.HOA.6&quot;&gt;
        ///&lt;![CDATA[
        ///Feed Slow]]&gt;
        ///&lt;/Commen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFile2 {
            get {
                return ResourceManager.GetString("TextFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WonderVerter {
            get {
                object obj = ResourceManager.GetObject("WonderVerter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;RSLogix5000Content SchemaRevision=&quot;1.0&quot; SoftwareRevision=&quot;30.00&quot; TargetName=&quot;SIR_Mixer8_Test_R1&quot; TargetType=&quot;Controller&quot; ContainsContext=&quot;false&quot; Owner=&quot;IQC&quot; ExportDate=&quot;Mon Mar 01 03:24:08 2021&quot; ExportOptions=&quot;NoRawData L5KData DecoratedData ForceProtectedEncoding AllProjDocTrans&quot;&gt;
        ///	&lt;Controller Use=&quot;Target&quot; Name=&quot;SIR_Mixer8_Test_R1&quot; ProcessorType=&quot;5069-L330ER&quot; MajorRev=&quot;30&quot; MinorRev=&quot;14&quot; ProjectCreationDate=&quot;Wed Dec 09 09:54:50 2020&quot; LastModifiedDat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLFile1 {
            get {
                return ResourceManager.GetString("XMLFile1", resourceCulture);
            }
        }
    }
}
